default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: seat_management_dev


test:
  <<: *default
  database: seat_management_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>